<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nbdownloader"
 *
 * Auto generated by Extension Builder 2015-11-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NetBrothers Downloader',
	'description' => 'Download files with counter, category, licence',
	'category' => 'plugin',
	'author' => 'Stefan Wessel',
	'author_email' => 'info@netbrothers.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'php' => '5.3.3-5.6.99',
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
